name: Manual Release

on:
  workflow_dispatch:
    inputs:
      release:
        type: choice
        required: true
        description: Release version
        options:
          - patch
          - minor
          - major
      tag:
        type: choice
        required: true
        description: Tag version
        options:
          - stable
          - beta

jobs:
  manual_release:
    runs-on: ubuntu-latest

    steps:
      - name: Get Email
        id: github_email
        uses: evvanErb/get-github-email-by-username-action@v1.25
        with:
          github-username: "${{ github.triggering_actor }}"
            
      - uses: actions/checkout@v3

      - uses: actions/setup-node@master
        with:
          node-version: 16.x
        env:
          RUNNER_TEMP: /tmp

      - name: Release selected
        run: echo "${{ github.event.inputs.release }}"
        
      - name: Tag selected
        run: echo "${{ github.event.inputs.tag }}"

      - name: Run Releasy
        id: release
        continue-on-error: true
        run: | 
            git config --global user.email "${{ steps.github_email.outputs.email }}"
            git config --global user.name "${{ github.triggering_actor }}"
            npx releasy ${{ github.event.inputs.release }} ${{ github.event.inputs.tag == 'stable' && '--stable' || '' }} --silent
        
      - name: Check Releasy
        run: "echo ${{ toJSON(steps.release) }}"
