name: Manual Release

on:
  workflow_dispatch:
    inputs:
      release:
        type: choice
        required: true
        description: Release version
        options:
          - patch
          - minor
          - major
          - patch:beta
          - minor:beta
          - major:beta

jobs:
  manual_release:
    runs-on: ubuntu-latest

    steps:
      - name: Get Email
        id: test
        uses: evvanErb/get-github-email-by-username-action@v1.25
        with:
          github-username: "${{ github.triggering_actor }}"
          
      - name: Print the found email
        run: echo "The email is ${{ toJSON(steps.test.outputs) }}"
    
      - uses: actions/checkout@v3

      - uses: actions/setup-node@master
        with:
          node-version: 16.x
        env:
          RUNNER_TEMP: /tmp

      - name: Run Releasy
        run: | 
            git config --global user.email "${{ steps.test.outputs.email }}"
            git config --global user.name "${{ github.triggering_actor }}"
            npx releasy ${{ github.event.inputs.release }} --stable --silent

      - name: Release selected
        run: echo "${{ github.event.inputs.release }}"
