name: Manual Release

on:
  workflow_dispatch:
    inputs:
      release:
        type: choice
        required: true
        description: Release version
        options:
          - patch
          - minor
          - major
          - patch:beta
          - minor:beta
          - major:beta

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Release selected
        run: echo "${{ github.event.inputs.release }}"
