name: Manual Release

on:
  workflow_dispatch:
    inputs:
      release:
        type: choice
        required: true
        description: Release version
        options:
          - patch
          - minor
          - major
          - patch:beta
          - minor:beta
          - major:beta

jobs:
  manual_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@master
        with:
          node-version: 16.x
        env:
          RUNNER_TEMP: /tmp
          
      - name: Dump GitHub context
        env:
          GITHUB_SECRETS: ${{ toJson(secrets) }}
        run: echo "$GITHUB_SECRETS"

      - name: Run Releasy
        run: npx releasy ${{ github.event.inputs.release }} --stable --silent

      - name: Release selected
        run: echo "${{ github.event.inputs.release }}"
