name: Manual Release

on:
  workflow_dispatch:
    inputs:
      release:
        type: choice
        required: true
        description: Release version
        options:
          - patch
          - minor
          - major
      tag:
        type: choice
        required: true
        description: Tag version
        options:
          - stable
          - beta

jobs:
  manual_release:
    runs-on: ubuntu-latest

    steps:
      - name: Get Email
        id: github_email
        uses: evvanErb/get-github-email-by-username-action@v1.25
        with:
          github-username: "${{ github.triggering_actor }}"
            
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
            ref: main
            token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@master
        with:
          node-version: 16.x
        env:
          RUNNER_TEMP: /tmp

      - name: Release selected
        run: echo "${{ github.event.inputs.release }}"
        
      - name: Tag selected
        run: echo "${{ github.event.inputs.tag }}"

      - name: Run Releasy
        run: | 
            git config --local user.name github-actions
            git config --local user.email github-actions@github.com
            npx releasy ${{ github.event.inputs.release }} ${{ github.event.inputs.tag == 'stable' && '--stable' || '' }} --silent
