name: Trigger Release on Merge

on:
  pull_request:
    types:
      - closed

jobs:
  trigger-release:
    if: |
      github.event.pull_request.merged == true &&
      github.event.pull_request.base.ref == github.event.repository.default_branch
    runs-on: ubuntu-latest
    steps:
      - name: Get labels
        id: get-labels
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const labels = pr.labels.map(label => label.name);
  
            const versionMap = {
              'release:patch': 'patch',
              'release:minor': 'minor',
              'release:major': 'major',
              'release:prerelease': 'prerelease',
            };
  
            const componentLabels = ['component:api', 'component:worker'];
  
            const selectedVersions = labels.filter(label => Object.keys(versionMap).includes(label));
            const selectedComponents = labels.filter(label => componentLabels.includes(label));
  
            const versionCount = selectedVersions.length;
            const componentCount = selectedComponents.length;
  
            if (versionCount === 0 && componentCount === 0) {
              console.log('ℹ️ No release or component labels selected — skipping release trigger.');
              core.setOutput('should_dispatch', 'false');
              return;
            }
  
            if (versionCount !== 1) {
              core.setFailed(`❌ You must apply exactly **one** version label when triggering a release.`);
              return;
            }
  
            if (componentCount === 0) {
              core.setFailed(`❌ At least **one** component label is required when a release label is selected.`);
              return;
            }
  
            const version = selectedVersions[0];
            const build_api = selectedComponents.includes('component:api');
            const build_wrk = selectedComponents.includes('component:worker');
  
            core.setOutput('release', versionMap[version]);
            core.setOutput('build_api', build_api);
            core.setOutput('build_wrk', build_wrk);

            core.setOutput('should_dispatch', 'true');

      - name: Dispatch Release Workflow
        if: steps.get-labels.outputs.should_dispatch == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'create-release-notes.yml',
              ref: context.payload.pull_request.base.ref,
              inputs: {
                release: '${{ steps.get-labels.outputs.release }}',
                build_api: '${{ steps.get-labels.outputs.build_api }}',
                build_wrk: '${{ steps.get-labels.outputs.build_wrk }}'
              }
            });
