name: Create Release Notes

on:
  workflow_dispatch:
    inputs:
      release:
        type: choice
        required: true
        description: Release type (version bump)
        options: [patch, minor, major, prerelease]
        default: patch

      build_api:
        type: boolean
        required: false
        description: Generate tag for API
        default: true

      build_wrk:
        type: boolean
        required: false
        description: Generate tag for Worker
        default: true

jobs:
  generate-tag:
    uses: ./.github/workflows/tag-generator.yml
    with:
      release: ${{ inputs.release }}
      tag: stable
      build_api: ${{ inputs.build_api }}
      build_wrk: ${{ inputs.build_wrk }}
    secrets: inherit

  generate-release-notes:
    needs: generate-tag
    runs-on: ubuntu-latest
    outputs:
      notes: ${{ steps.notes.outputs.release_notes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate release notes
        id: notes
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;

            const result = await github.rest.repos.generateReleaseNotes({
              owner,
              repo,
              tag_name: '${{ needs.generate-tag.outputs.api_tag || needs.generate-tag.outputs.wrk_tag }}',
            });

            const filtered = result.data.body
              .split('\n')
              .filter(line => !/@dk-(cicd|portal)/.test(line))
              .join('\n');

            core.setOutput('release_notes', filtered);

  release-api:
    needs: [generate-tag, generate-release-notes]
    if: ${{ inputs.build_api }}
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub release for API
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.generate-tag.outputs.api_tag }}
          body: ${{ needs.generate-release-notes.outputs.notes }}

  release-wrk:
    needs: [generate-tag, generate-release-notes]
    if: ${{ inputs.build_wrk }}
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub release for Worker
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.generate-tag.outputs.wrk_tag }}
          body: ${{ needs.generate-release-notes.outputs.notes }}
